version: "1"
services:

  aggregator:
    image: myorg/myapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    restart: unless-stopped

  postgres_db:
    image: postgres:11.8
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U compose-postgres -d compose-postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data